AcademicSpyware/AcademicSpyware/Controllers/ComputerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AcademicSpyware.Models;
using AcademicSpyware.Models.ViewModel;

namespace AcademicSpyware.Controllers
{
    public class ComputerController : Controller
    {
        private SpywareDBEntities db = new SpywareDBEntities();

        /// <summary>
        ///     Purpose: Shows a list of wings
        /// </summary>
        /// <returns>GET: /Computer/</returns>
        public ActionResult Index()
        {
            return View(db.View_BuildingWing.ToList());
        }

        /// <summary>
        ///     Purpose: Shows a list of history based on the building ID
        /// </summary>
        /// <param name="ID">Building Name</param>
        /// <returns> GET: /Computer/DetailRoom/ID</returns>
        public ActionResult DetailRoom(string ID)
        {
            var result = db.DetailHistoryViews.Where(w => w.Building == ID).ToList();

            return View(result);
        }

        /// <summary>
        ///     Purpose: Shows a history based on the building ID and seperate 
        ///              the Rooms into the DetailViewModel
        /// </summary>
        /// <param name="ID"></param>
        /// <returns>GET: /Computer/Building/ID</returns>
        public ActionResult Building(string ID)
        {
            var result = db.DetailHistoryViews.Where(w => w.Building == ID).ToList();
            var building = db.View_BuildingWing.ToList();

            DetailViewModel dvm = new DetailViewModel();

            foreach (var i in result.Select(w => w.Room).Distinct())
            {
               var sectionItem  = result.Where(c => c.Room == i);

               dvm.section.Add(new SectionViewModel() { items = sectionItem.OrderByDescending(c => c.Description).ToList() });
            }

            dvm.BuildingWing = building;

            dvm.building = ID;

            return View(dvm);
        }

    }
}

AcademicSpyware/AcademicSpyware/Views/Shared/_HeaderPartial.cshtml
<div class="masthead">





    <div id="navBar">
        
    <ul class="nav nav-pills pull-right">
        
        <br /><br />
        <li class="active">@Html.ActionLink("Home", "Index", "Home")</li>
        <li class="active">@Html.ActionLink("About","About","Home")</li>
        <li class="active">@Html.ActionLink("Computers","Index","Computer")</li>
            @Html.Partial("_LoginPartial")
    </ul>

        </div>


    <h3 class="muted">
         <a href="/"><img src="~/Images/global/logo_small.png" /></a>
        
    </h3>
    <hr style="width:50%" />

</div>

AcademicSpyware/AcademicSpyware/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>Academic &middot; Spyware</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">


    <!-- Le javascript
    ================================================== -->
    
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.9.1/jquery-ui.min.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>

    <script src="~/Scripts/Slides/slides.jquery.js"></script>


    <!-- Le styles -->
    <link href="~/Content/bootstrap/bootstrap.css" rel="stylesheet">
    <link href="~/Content/bootstrap/bootstrap-responsive.css" rel="stylesheet">
    <link href="~/Content/Site.css" rel="stylesheet">

    <!-- Fav and touch icons -->
    <link rel="shortcut icon" href="~/animated_favicon1.gif">
</head>

<body>
    
    <div class="container-narrow">
        @Html.Partial("_HeaderPartial")
        <div id="sample">
                
            
                  @RenderBody()
        </div>
</div>
</body>
</html>